steps:
  # Paso 1: Construir la imagen desde el Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/empprimaria/api-emp:latest', '.']

  # Paso 2: Subir la imagen al registro de contenedores
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/empprimaria/api-emp:latest']

  # Paso 3: Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'servicio-api-emp',
        '--image', 'gcr.io/empprimaria/api-emp:latest',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '3000'
      ]

options:
  logging: CLOUD_LOGGING_ONLY