steps:
  # Paso 1: Construir la imagen desde el Dockerfile dentro de api-login
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/login-488119/api-login:latest',
      '-f', 'api-login/Dockerfile',
      'api-login'
    ]

  # Paso 2: Subir la imagen al registro de contenedores
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/login-488119/api-login:latest']

  # Paso 3: Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'servicio-api-login',
        '--image', 'gcr.io/login-488119/api-login:latest',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '3000'
      ]

options:
  logging: CLOUD_LOGGING_ONLY