steps:
  # Paso 1: Construir la imagen desde el Dockerfile dentro de api-accident-reporter
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/accidentreporter-488120/api-ar:latest',
      '-f', 'Rep-Apis/api-accident-reporter/Dockerfile',
      'Rep-Apis/api-accident-reporter'
    ]

  # Paso 2: Subir la imagen al registro de contenedores
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/accidentreporter-488120/api-ar:latest']

  # Paso 3: Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'servicio-api-ar',
        '--image', 'gcr.io/accidentreporter-488120/api-ar:latest',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '3000'
      ]

options:
  logging: CLOUD_LOGGING_ONLY